name: examples
description: Flutter examples for March 19

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_bloc: ^0.3.0
  transparent_image: 1.0.0

flutter:
  uses-material-design: true
